name: Run unit tests on pushes to feature branches

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request towards the branch below
  push:
    branches:
      - 'feature/**'

  # Allows you to run this workflow manually from the Actions tab
  ? workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  execute-unit-tests:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      CONFIG_PATH: './dtc.config.json'
      TEMPLATE_DIR: './templates'
      OUTPUT_PATH: './outputs'
      SKETCH_TOOL_PATH: '/Applications/Sketch.app/Contents/MacOS/sketchtool'
      # Use my figma file named `sample_for_test`
      FIGMA_FILE_KEY: 'RL6HzoX6UeVaQw4OmSsqxr'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install sketch
        run: scripts/install_sketch.sh
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.16.0'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build project
        run: npm run build
      - name: Run test
        run: npm run test
